Repository astral-sh/setup-uv, pull requests merged in 2024-12, with the labels that each got.

#184 Add hint why cache-dependency-glob fails
  dist/save-cache/index.js
  dist/setup/index.js
  src/cache/restore-cache.ts
Labels: documentation, bugfix

#185 Add **/requirements*.txt to default cache-dependency-glob
  .github/workflows/test-cache.yml
  README.md
  __tests__/fixtures/requirements-txt-project/hello_world.py
  __tests__/fixtures/requirements-txt-project/requirements.txt
  action.yml
Labels: documentation, enhancement, breaking-change

#186 Update dependencies
  dist/save-cache/index.js
  dist/setup/index.js
  dist/update-known-checksums/index.js
  package-lock.json
  package.json
Labels: dependencies

#191 Always use api.github.com
  dist/setup/index.js
  dist/update-known-checksums/index.js
  src/download/download-version.ts
  src/update-known-checksums.ts
  src/utils/constants.ts
Labels: bugfix

#193 Default to enable-cache: true on GitHub hosted runners
  .github/workflows/test-cache.yml
  .github/workflows/test.yml
  action.yml
  dist/save-cache/index.js
  dist/setup/index.js
  src/utils/inputs.ts
Labels: enhancement, breaking-change

#187 Add python version to cache key
  .github/workflows/test-cache.yml
  __tests__/fixtures/old-python-constraint-project/README.md
  __tests__/fixtures/old-python-constraint-project/pyproject.toml
  __tests__/fixtures/old-python-constraint-project/src/old_python_constraint_project/__init__.py
  __tests__/fixtures/old-python-constraint-project/uv.lock
  dist/save-cache/index.js
  dist/setup/index.js
  src/cache/restore-cache.ts
Labels: enhancement

#194 Auto activate venv when python-version is set
  .github/workflows/test.yml
  README.md
  action.yml
  dist/setup/index.js
  src/setup-uv.ts
Labels: enhancement

#200 Warn instead of fail for no-dependency-glob
  dist/save-cache/index.js
  dist/setup/index.js
  src/cache/restore-cache.ts
Labels: bugfix

#201 Fix wrong cacheDependencyPathHash
  dist/save-cache/index.js
  dist/setup/index.js
  src/cache/restore-cache.ts
Labels: bugfix

#207 Align use of `actions/setup-python` with uv docu
  README.md
Labels: documentation

#210 Set VIRTUAL_ENV to .venv instead of .venv/bin
  dist/setup/index.js
  src/setup-uv.ts
Labels: bugfix

#205 docs: bump `astral-sh/setup-uv` to `v5`
  README.md
Labels: documentation
