Repository astral-sh/setup-uv, pull requests merged in 2024-09, with the labels that each got.

#24 Add default-version-update category
  .github/release-drafter.yml
  .github/workflows/update-default-version.yml
Labels: maintenance

#33 Rename repo org in examples and urls
  README.md
  package.json
Labels: documentation

#34 Add acknowledgements and Astral logo
  README.md
  docs/images/bmc-button.svg
  docs/images/paypal-button.svg
Labels: documentation

#46 Make some minor edits to the README
  README.md
Labels: documentation

#51 Run test build only on ubuntu-latest
  .github/workflows/test.yml
Labels: ci

#53 Always run check-dist check
  .github/workflows/check-dist.yml
Labels: ci

#41 Support a list of cache-dependency-glob
  .github/workflows/test-cache.yml
  README.md
  dist/save-cache/index.js
  dist/save-cache/index.js.map
  dist/save-cache/sourcemap-register.js
  dist/setup/37.index.js
  dist/setup/37.index.js.map
  dist/setup/index.js
  dist/setup/index.js.map
  dist/setup/licenses.txt
  dist/setup/sourcemap-register.js
  dist/update-checksums/index.js
  dist/update-checksums/index.js.map
  dist/update-checksums/sourcemap-register.js
  dist/update-default-version/index.js
  dist/update-default-version/index.js.map
  dist/update-default-version/sourcemap-register.js
  src/cache/restore-cache.ts
Labels: enhancement

#50 Update README to v2
  README.md
Labels: documentation

#59 rename utils/utils.ts to constants.ts
  dist/setup/index.js
  dist/update-known-checksums/index.js
  src/download/download-latest.ts
  src/download/download-version.ts
  src/update-known-checksums.ts
  src/utils/constants.ts
Labels: maintenance

#76 Add .idea files to gitignore
  .gitignore
Labels: maintenance

#77 Set the cache-dependency-glob default to `**/uv.lock`
  README.md
  action.yml
Labels: documentation, breaking-change

#78 Run prettier
  .github/workflows/test.yml
  README.md
  action.yml
Labels: maintenance

#80 Fix prettier destroying markdown NOTE
  README.md
Labels: documentation

#82 Add support for semver version ranges
  .github/workflows/test.yml
  README.md
  dist/setup/index.js
  src/download/download-version.ts
  src/setup-uv.ts
Labels: enhancement

#85 Update version in README from v2 to v3
  README.md
Labels: documentation

#90 Fix a typo SHA265 → SHA256
  README.md
Labels: documentation

#96 Use runner label selfhosted-ubuntu-arm64
  .github/workflows/test-cache.yml
  .github/workflows/test.yml
Labels: documentation

#97 Only log checksum is valid when it really is
  dist/setup/index.js
  src/download/checksum/checksum.ts
Labels: bugfix

#107 Migrate to Biome for linting and formatting
  .eslintignore
  .eslintrc.json
  .prettierignore
  .prettierrc.json
  biome.json
  dist/save-cache/index.js
  dist/setup/index.js
  dist/update-known-checksums/index.js
  package-lock.json
  package.json
  src/download/checksum/checksum.ts
  src/download/checksum/update-known-checksums.ts
  src/download/download-latest.ts
  src/download/download-version.ts
  src/save-cache.ts
  src/setup-uv.ts
  src/utils/inputs.ts
Labels: maintenance
