Repository astral-sh/setup-uv, pull requests merged in 2024-10, with the labels that each got.

#121 Update deps
  dist/save-cache/index.js
  dist/setup/index.js
  dist/update-known-checksums/index.js
  package-lock.json
  package.json
Labels: javascript, maintenance

#128 Use 0.4.x for versioning examples
  README.md
Labels: documentation

#134 feat: add option to disable cache pruning
  README.md
  action.yml
  dist/save-cache/index.js
  dist/setup/index.js
  src/save-cache.ts
  src/utils/inputs.ts
Labels: enhancement
