Repository astral-sh/setup-uv, pull requests merged in 2024-11, with the labels that each got.

#148 add archive extension to downloaded assets
  dist/setup/index.js
  src/download/download-latest.ts
  src/download/download-version.ts
Labels: bugfix

#150 Avoid leftover files by using temp dir
  dist/setup/index.js
  src/download/download-latest.ts
  src/download/download-version.ts
Labels: bugfix

#161 Add comment to clarify process.exit(0)
  dist/save-cache/index.js
  src/save-cache.ts
Labels: documentation

#162 Remove working dir from cacheDependencyGlob error message
  dist/save-cache/index.js
  dist/setup/index.js
  src/cache/restore-cache.ts
Labels: bugfix

#163 Fail when cache local path does not exist when trying to cache
  .github/workflows/test-cache.yml
  README.md
  action.yml
  dist/save-cache/index.js
  dist/setup/index.js
  src/save-cache.ts
  src/utils/inputs.ts
Labels: bugfix, breaking-change

#164 Change some formulations in README.md
  README.md
Labels: documentation

#165 Clarify caching will only fail when enabled and nothing to cache
  README.md
Labels: documentation

#166 Speed up updating known checksums
  dist/setup/index.js
  dist/update-known-checksums/index.js
  package.json
  src/download/checksum/known-checksums.ts
  src/download/checksum/update-known-checksums.ts
Labels: ci

#173 Reduce test matrices
  .github/workflows/test-cache-windows.yml
  .github/workflows/test-cache.yml
  .github/workflows/test.yml
Labels: ci

#174 Add input python-version
  .github/workflows/test.yml
  README.md
  action.yml
  dist/save-cache/index.js
  dist/setup/index.js
  src/setup-uv.ts
  src/utils/inputs.ts
Labels: enhancement

#175 Add matrix example for python-version
  README.md
Labels: documentation

#176 Replace v3 with v4 in README.md
  README.md
Labels: documentation

#177 Add test for python-version
  .github/workflows/test.yml
Labels: ci

#178 Resolve latest version instead of downloading latest release
  README.md
  dist/setup/index.js
  src/download/download-latest.ts
  src/download/download-version.ts
  src/setup-uv.ts
Labels: enhancement
